version: '3.8'

services:
  app:
    build: .
    container_name: python_app
    environment:
      - DATABASE_URL=postgresql://postgres:4771@db:5432/Test_task
    ports:
      - "8000:8000"
    depends_on:
      - db

    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=Test_task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4771
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
